### ISSUE TITLE
Bandwidth Specification Change

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#177]
List of Proposal:

- [x] Bandwidth Respect Price Bug #168 
- [x] Change Createa Validator Msg cost #178
- [x] Bandwidth price to average for 24h window #179
