### ISSUE TITLE
Launch 0.1.1 testnet

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#205]
Currently, we are at the point. where we want to relauch our testnet. There are view reasons here: consensus bug, new cosmos-sdk and tendermint versions, various spec improvements, wrong genesis allocations, main token renaming and etc.

As said before, we are using the concept of useful testnets, so all data (balances and links, validators and delegators) will be moved to the new testnet.

Issue list to go:
- [x] #156 Wrong CYB Allocation
- [x] #184 Links Exporter
- [x] #157 Rename token
- [x] #177 Bandwidth specification change
- [x] #187 Update Tendermint and Cosmos
- [x] #201 Redefine consenus params 
- [x] #197 Consensus failure bug
- [x] #171 Reduce Tx size for links
- [x] #160 Genesis file distribution 
- [x] #215 Export 0.1.0 state to genesis 0.1.1
