### ISSUE TITLE
Create cyberd PoC based on Cosmos SDK

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyberd#37]
- [x] Basic rank implementation in Golang Cosmos SDK
- [x] RPC API for querying application state
- [x] Basic CLI (querying app state, sign transactions, key managment)

**Comment by hleb-albau** [comment]
Basic implementation is done. Next #73 !

**Comment by hleb-albau** [comment]
Basic implementation is done. Next #73 !
